import { JetBrains_Mono} from "next/font/google";
import "./globals.css";

<link href="https://fonts.googleapis.com/css2?family=Noto+Nastaliq+Urdu&display=swap" rel="stylesheet" />


import Header from "@/components/Header";
import Page from "@/components/pagetransitons";
import Stairtransition from "@/components/StairTransition";

const JetBrainsMono = JetBrains_Mono({ subsets: ["latin"  ],
  weight: ["100","200","300","400","500","600","700","800"],
  variable: '--font-JetBrains-mono', });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={JetBrainsMono.variable}>
        <Header/>
        <Stairtransition/>
        <Page>{children}</Page>
              
        
       
        
        </body>
    </html>
  );
}
